<a href="https://colab.research.google.com/github/SokichiFujita/PyTorch-for-Deep-Learning-and-Computer-Vision/blob/master/Chapter3_2DimensionalTensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [11]:
one_d = torch.arange(0,9)
print(one_d)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])


In [12]:
two_d = one_d.view(3,3)
print(two_d)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [14]:
print(two_d.dim())

2


In [18]:
print(two_d[0,0])
print(two_d[0,1])
print(two_d[1,0])

tensor(0)
tensor(1)
tensor(3)


In [20]:
x = torch.arange(18).view(3,3,2)
print(x)

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]]])
