<a href="https://colab.research.google.com/github/SokichiFujita/PyTorch-for-Deep-Learning-and-Computer-Vision/blob/master/Chapter3_Matrix_Multiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [13]:
matrix_a = torch.tensor([0,3,1,2,0,1]).view([2,3])
print(matrix_a)

tensor([[0, 3, 1],
        [2, 0, 1]])


In [14]:
matrix_b = torch.tensor([1,2,3,5,6,1]).view([3,2])
print(matrix_b) 

tensor([[1, 2],
        [3, 5],
        [6, 1]])


In [15]:
matrix_c = matrix_a @ matrix_b
print(matrix_c)

tensor([[15, 16],
        [ 8,  5]])
