<a href="https://colab.research.google.com/github/SokichiFujita/PyTorch-for-Deep-Learning-and-Computer-Vision/blob/master/Tensors_Crash_Course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip3 install torch

In [4]:
import torch

tensor([1, 2, 3])
torch.int64
tensor(2)


In [8]:
v = torch.tensor([1,2,3,4,5,6])
print(v)
print(v.dtype)
print(v[1:4])
print(v[1:])

tensor([1, 2, 3, 4, 5, 6])
torch.int64
tensor([2, 3, 4])
tensor([2, 3, 4, 5, 6])


In [11]:
f = torch.FloatTensor([1,2,3,4,5,6])
print(f)
print(f.dtype)
print(f.size())

tensor([1., 2., 3., 4., 5., 6.])
torch.float32
torch.Size([6])


In [12]:
v.view(6,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [17]:
v.view(6,1)

RuntimeError: ignored

In [18]:
v.view(7,1) #error

RuntimeError: ignored

In [19]:
v.view(3,-1)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [23]:
v.view(3,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [24]:
v.view(2,3)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [0]:
import numpy as np

In [32]:
a = np.array([1,2,3,4,5])
print(a)
tensor_from_numpy = torch.from_numpy(a)
print(tensor_from_numpy)
numpy_from_tensor = tensor_from_numpy.numpy()
print(numpy_from_tensor)


[1 2 3 4 5]
tensor([1, 2, 3, 4, 5])
[1 2 3 4 5]
